services:
  freeradius:
    container_name: freeradius
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
    privileged: true
    env_file:
      - .env
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
